apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          # image: us.gcr.io/ticketing-dev-372602/auth
          image: yangzhou12138/expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_URL
              value: "http://nats-srv:4222"
            - name: NATS_CLUSTER_ID
              value: ticketing
            # unique client_id for every client that connects to NATS (copys of tickets microservice)
            # the name of each pod is unique
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
